# [lru]
# capacity = 64

# [semanticHighlighting]
# operator.enable = false
# punctuation.enable = false
# strings.enable = false
# nonStandardTokens = false

[files]
exclude = ["flatpak-builder-tools", "cosmic-flatpak-runtime",
           "flatpak-out", "mupdf", "build-dir", ".zed", "mupdf-cargo-sources.json", "cargo-sources.json"]