on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
        - run: nix develop
