pub mod ffmpeg;
mod file_helper;
pub mod image_model;
pub mod models;
pub mod presentation_model;
pub mod reveal_js;
pub mod schema;
mod service_item_model;
// mod service_thing;
pub mod settings;
pub mod slide_model;
mod slide_obj;
pub mod songs;
pub mod video_model;
pub mod ytdl;
pub mod utils;
// mod video_thumbnail;
